### ISSUE TITLE
Info's on how to use it

### ISSUE THREAD

**Issue by maudit-4047** [hclivess/itunes-downloader#1]
I m a normal person it will be very handy if u can provide how to make it work thanks

**Comment by hclivess** [comment]
Hi, you need to obtain `list.plist`, which is an iTunes playlist. This tool was designed to download using playlists.

**Comment by maudit-4047** [comment]
hello is it possible to make it work for movies ?

**Comment by hclivess** [comment]
the playlist needs to contain links to the files you want to download
